AWSTemplateFormatVersion: 2010-09-09
Description: Simple Static Website 
  For this template to work properly, you have to upload two files 
    index.html
    error.html
  to the created S3 bucket, these files should be working html files
    In the next version of this template, consider creating a custom resource that creates these two files for you

Metadata:
  'AWS::CloudFormation::Designer':
    bb42ec1f-6b3e-418c-b9e4-9f81e81773b7:
      size:
        width: 60
        height: 60
      position:
        x: 20
        'y': 110
      z: 0
      embeds: []
    c33aeeb6-4502-4188-aebd-717e39a8767d:
      size:
        width: 60
        height: 60
      position:
        x: 140
        'y': 80
      z: 0
      embeds: []
Resources:
  myBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    Metadata:
      'AWS::CloudFormation::Designer':
        id: bb42ec1f-6b3e-418c-b9e4-9f81e81773b7
  myBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref myBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicRead
            Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
              - 's3:GetObjectVersion'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref myBucket
                - /*
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c33aeeb6-4502-4188-aebd-717e39a8767d
Outputs:
    thisIsMyUrl:
        Value:
            !GetAtt myBucket.WebsiteURL
        Description: This Is My Bucket URL
    thisIsMyDNS:
        Value:
            !GetAtt myBucket.DomainName
        Description: This Is My Bucket DomainName
